on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude=".git" --include="" --filter=""
        path: .
        remote_path: ${{ secrets.DESTINATION }}
        remote_host: gate.cloudjiffy.com
        remote_port: 3022
        remote_user: '180022-3496'
        remote_key: ${{ secrets.SSH_KEY }}

