on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude=".git,.github" --include="" --filter=""
        path: .
        remote_path: ${{ secrets.DESTINATION }}
        remote_host: ${{ secrets.WP_HOST }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: '${{ secrets.SSH_USERNAME }}'
        remote_key: ${{ secrets.SSH_KEY }}

