on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: 'gate.cloudjiffy.com'
        port: 3022
        username: '180022-3496'
        privateKey: ${{ secrets.SSH_KEY }}
        localPath: '/home/runner/work/git-plugin/git-plugin/'
        remotePath: '/var/www/webroot/ROOT/wp-content/plugins/git-plugin/'
          
